host "localhost:3000" {
    proxy_pass http://localhost:8000;
}

host "192.168.1.208:3000"{
    proxy_pass http://192.168.1.208:8000;
    proxy_pass http://192.168.1.208:8001;
    proxy_pass http://192.168.1.208:8002;
    dist_policy least-conn
}

host "10.230.199.13:3000"{
    proxy_pass http://10.230.199.13:8000;
    proxy_pass http://10.230.199.13:8001;
    proxy_pass http://10.230.199.13:8002;
    dist_policy least-conn
}



host "app1.local" {
    proxy_pass http://192.168.56.103:9001;
}

host "app2.local" {
    proxy_set_header Host $host;

    proxy_pass http://192.168.56.210:9002;
    proxy_pass http://192.168.56.220:9002;
	

    dist_policy round-robin
}
